USE [master]
GO

/****** Object:  Database [PARTNERGROUP]    Script Date: 01/03/2019 15:28:14 ******/
CREATE DATABASE [PARTNERGROUP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PARTNERGROUP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\PARTNERGROUP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PARTNERGROUP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\PARTNERGROUP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [PARTNERGROUP] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PARTNERGROUP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PARTNERGROUP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET ARITHABORT OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PARTNERGROUP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PARTNERGROUP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PARTNERGROUP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PARTNERGROUP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PARTNERGROUP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PARTNERGROUP] SET  MULTI_USER 
GO

ALTER DATABASE [PARTNERGROUP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PARTNERGROUP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PARTNERGROUP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PARTNERGROUP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PARTNERGROUP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PARTNERGROUP] SET QUERY_STORE = OFF
GO

USE [PARTNERGROUP]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [PARTNERGROUP] SET  READ_WRITE 
GO

